### ISSUE TITLE
도커 실행 후 로그에 보면 load lang fail이라고 뜹니다.

### ISSUE THREAD

**Issue by tenziro** [acidpop/synobot_public#5]
기본 환경변수로 설정된 LANG의 문제인가 싶어 해당 부분을 삭제 후에
SYNO_LANG : ko_kr을 남겨두었는데도 계속 발생합니다.

**Comment by acidpop** [comment]
해당 이슈는 무시하셔도 됩니다. 코드에서 로컬라이징 파일을 읽는 코드가 있는데 실패 하는 경우 메시지를 출력을 하고 있어서 그렇습니다.

다만, 아직 로컬라이징은 작동이 안되도록 해놔서 무시 하셔도 되는 로그입니다.
