### ISSUE TITLE
다운로드 폴더 지정 기능 추가 요청

### ISSUE THREAD

**Issue by ohnggni** [acidpop/synobot_public#6]
안녕하세요? 좋은 프로그램 감사드립니다.
추가적으로,
다운로드 폴더를 환경변수에 지정하는 기능을 추가해주실 수 있을까요?

**Comment by acidpop** [comment]
해당 기능을 추가하는건 어렵지 않은데 잘못된 경로를 넣었을 경우에 대한 예외 처리 로직이 필요해서..
대응 하는게 좀 어렵습니다.

**Comment by ohnggni** [comment]
아, 그렇군요. 감사합니다.
